### PR TITLE
config files will no longer be saved until props files are saved

### LINKED ISSUE #23: Bug Bash: Tool logs errors downloading NuGet packages but succeeds
Command line:

```
C:\src\_test\insertions\VS Repo>C:\src\insertions-client\src\InsertionsClient\bin\Debug\netcoreapp3.1\InsertionsClient.exe -d:"C:\src\_test\insertions\VS Repo\.corext\Configs\default.config" -m:"..\Aux Files\sample_manifest.json"
```

Log output:

```
21-4-2020 12:38:47.672526|thread:1|The directory to search for .props files: C:\src\_test\insertions\VS Repo\src\SetupPackages
21-4-2020 12:38:49.648488|thread:13|There is an issue downloading nuget package: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/devdiv/_packaging/VS-CoreXtFeeds/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at Microsoft.Net.Insertions.Api.PropsVariableDeducer.GetPackageFileList(DefaultConfigUpdater defaultConfigUpdater, PackageUpdateResult packageUpdate) in C:\src\insertions-client\src\InsertionsClient\Api\Props\PropsVariableDeducer.cs:line 122

...

Completed successfully.
```

Running the tool again with the same command line but without undoing the changes it's made to config files does not log the errors anymore.

1. Why doesn't the NuGet failure cause the tool to fail?
2. Why does it behave differently depending on the state of the config files?

### PR DESCRIPTION
**Pull request by bozturkMSFT**
Fixes #23 

Problem: If config files are updated and props file updates fail, local repo gets into a partially updated state. In this state, re-running the tool doesn't attempt to update props files anymore, because all the packages appear to be up-to-date.

To prevent this, config file saves are delayed now until props files are successfully saved.

I also updated help text to make the following obvious: not specifying an access token will result in no props file being updated.

### CODE REVIEW

File: src/InsertionsClient/Api/Providers/InsertionApi.cs [hunk 1]
```diff
@@ -71,46 +71,72 @@ public UpdateResults UpdateVersions(string manifestFile, string defaultConfigFil
                     CreateParallelOptions(source.Token),
                     asset => ParallelCallback(asset, packagesToIgnore, configUpdater, results));
 
-                results.FileSaveResults = configUpdater.Save();
+                /* Delay saving config file changes until props file updates are successfull.
```
Comment (ladipro) [inline src/InsertionsClient/Api/Providers/InsertionApi.cs:74]: nit: typo ```successfull```

File: src/InsertionsClient/Api/Providers/InsertionApi.cs [hunk 2]
```diff
@@ -71,46 +71,72 @@ public UpdateResults UpdateVersions(string manifestFile, string defaultConfigFil
...
+                            Trace.WriteLine($"The directory to search for .props files: {propsFilesRootDirectory}");
+                        }
+                        else
                         {
-                            Outcome = false,
-                            OutcomeDetails = "Failed to find an appropriate folder to search for .props files."
-                            + "Props file updating will be disabled."
-                        };
+                            Trace.WriteLine("Failed to find an appropriate folder to search for .props files."
+                                + "Props file updating will be disabled.");
```
Comment (ladipro) [inline src/InsertionsClient/Api/Providers/InsertionApi.cs:93]: nit/preexisting: missing space between the two sentences
